# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift Demo Cluster'

- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift Demo Cluster'
    cmd: 'oc start-build jws-app --follow'
    uselocalOc: true
- task: oc-cmd@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift Demo Cluster'
    cmd: 'oc status'
    uselocalOc: true

- script: echo Hello, world!
  displayName: 'Run a one-line script'
