# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo $(rhv_vm_name)
    echo $(tower_group)
    echo $(tower_inventory)
    echo $(vm_fq_hostname)
  displayName: 'Display Ansible Tower job parameters'

- script: |
    curl http://google.com
  displayName: 'Execute Ansible Tower template'
