# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build_stage
  jobs:
  - job: build_job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: oc-setup@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift Demo Cluster'

    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift Demo Cluster'
        cmd: 'oc start-build hello -n development --follow'
        uselocalOc: true
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift Demo Cluster'
        cmd: 'oc status'
        uselocalOc: true

- stage: test_stage
  jobs:
  - deployment: deployToTest
    displayName: Deploy to Test environment
    pool:
      vmImage: 'ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: oc-setup@2
            inputs:
              connectionType: 'OpenShift Connection Service'
              openshiftService: 'OpenShift Demo Cluster'

          - script: oc tag `oc describe imagestream hello -n development |grep sha256|grep -m 1 "\*"|cut -d / -f 2,3` development/hello:promoteToTest
            displayName: 'Tag the new container image'
