apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"dockereap:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"dockereap\")].image"}]'
  generation: 2
  labels:
    app: dockereap
    app.kubernetes.io/component: dockereap
    app.kubernetes.io/instance: dockereap
  name: dockereap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: dockereap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: dockereap
    spec:
      containers:
      - image: quay.io/tprinz/dockereap@sha256:c542191d0bdb87622fb69de6d4a8827416247fb56c7a6405900ab5bd255dc093
        imagePullPolicy: IfNotPresent
        name: dockereap
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
